/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your .gitignore.
// It is auto-generated by Expo, mas mantido versionado aqui para garantir
// os tipos no ambiente de CI/sandbox quando o Expo ainda não foi instalado.
